### PR TITLE
Math Magicians: Components

### PR DESCRIPTION
**Pull request by WilhelmK109**
### In this milestone of the project, I did the following:
- Developed the math magicians calculator user interface.
- Deleted all the boilerplate from Create React App such as text, images, and style.
- Added the calculator Components.
- Added CSS styling to match the calculator design.

### CODE REVIEW

**Review by t-yanick — APPROVED** [review]
# STATUS: MILESTONE APPROVED :1st_place_medal: 

Hi @WilhelmK109 , 

### Great job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Project folder well structured
:heavy_check_mark: Calculator.js is a functional component
:heavy_check_mark:  Good commit messages
:heavy_check_mark: Descriptive Readme file and PR

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## Optional suggestions

- [ OPTIONAL] 
Consider removing your github repo link from the MIT license section

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by WilhelmK109** [comment]
@t-yanick thanks for the approval of my PR. I have a question: Why should I remove the GitHub repo link if it directs people to the MIT Licence?

**Comment by t-yanick** [comment]
> @t-yanick thanks for the approval of my PR. I have a question: Why should I remove the GitHub repo link if it directs people to the MIT Licence?

I think the MIT link is already there that does the job. When I click on MIT I am directed to the license page

**Comment by WilhelmK109** [comment]
@t-yanick, Okay thank you. Now I understand.

**Pull request merged**
