### PR TITLE
Math Magicians: tests

### PR DESCRIPTION
**Pull request by WilhelmK109**
### In this milestone of the project, we did the following:
- Added tests to the Math Magicians app using Jest and React Testing Library.
- Wrote unit tests for the files operate.js and calculate.js using Jest.
- Created unit tests for all React components.
- Used Jest snapshots to test the components.
- Used React Testing Library to simulate user interaction.

### CODE REVIEW

**Review by roshan-bajgain — APPROVED** [review]
Hi @WilhelmK109 and @ankitt26, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- All test are passing ✔️ 

## Optional suggestions
- [ ] If you decide not to deploy the app then please remove it. It makes your README file more professional and descriptive.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by WilhelmK109** [comment]
@roshan-bajgain, thank you very much for the approval of the PR, sir. May you perhaps clarify more on what I should remove, I did not get your point well.

**Comment by roshan-bajgain** [comment]
Hello @WilhelmK109, In your README file there is a live demo heading that is not deployed so if you do want not to deploy the app then please remove it from README. I think you got it, I am sorry for not making you understand.
Screenshot 2023-06-08 174109

**Comment by WilhelmK109** [comment]
@roshan-bajgain, Okay sir, I now understand. I will deploy the project and update the readme file. Thank you once more again.

**Pull request merged**
